apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pythonapp.fullname" . }}
  labels:
    {{ include "pythonapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{ include "pythonapp.labels" . | nindent 4 }}
  template:
    metadata:
      labels:
        {{ include "pythonapp.labels" . | nindent 4 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port | default 80 }}
              protocol: TCP
          {{ if .Values.env }}
          env:
            - name: ENV
              value: {{ .Values.env.ENV | default "unknown" | quote }}
            - name: IMAGE
              value: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          {{ end }}