{{- if .Values.ingress.enabled }}
{{- $certName := index .Values.ingress.annotations "networking.gke.io/managed-certificates" | default "" -}}
{{- if $certName }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ $certName }}
  labels:
    app: {{ .Release.Name }}
spec:
  domains:
    - {{ .Values.ingress.tls.domain | quote }}
{{- end }}
{{- end }}
