apiVersion: v1
kind: Service
metadata:
  name: {{ include "pythonapp.fullname" . }}
  labels:
    {{- include "pythonapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- include "pythonapp.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
