image:
  repository: asia-northeast3-docker.pkg.dev/rs-2024-00460435-456102/hwgar/python-app
  pullPolicy: IfNotPresent
  tag: "29257648c2995cb7e58c281b4d8f13dfc5e5589e"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000
