image:
  repository: asia-northeast3-docker.pkg.dev/rs-2024-00460435-456102/hwgar/python-app
  pullPolicy: IfNotPresent
  tag: "dev-0106T1553"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000
