name: push-to-gar

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: python-app
  GAR_REGISTRY: asia-northeast3-docker.pkg.dev
  GCP_PROJECT_ID: rs-2024-00460435-456102
  GAR_REPOSITORY: hwgar


jobs:
  build-and-push:
    runs-on: [self-hosted, arc-org]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
  
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: projects/327030237750/locations/global/workloadIdentityPools/github/providers/github
          service_account: 327030237750-compute@developer.gserviceaccount.com
          project_id: rs-2024-00460435-456102

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: asia-northeast3-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.GAR_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:dev-0106T1553

