name: push-to-gar

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: python-app
  GAR_REGISTRY: asia-northeast3-docker.pkg.dev
  GCP_PROJECT_ID: rs-2024-00460435-456102
  GAR_REPOSITORY: hwgar


jobs:
  build-and-push:
    runs-on: [self-hosted, arc-org]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
  
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: projects/327030237750/locations/global/workloadIdentityPools/github/providers/github
          service_account: 327030237750-compute@developer.gserviceaccount.com
          project_id: rs-2024-00460435-456102

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: asia-northeast3-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.GAR_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest


# name: CI Build & Push to GAR

# on:
#   push:
#     branches: ["main"]
#   workflow_dispatch:

# env:
#   IMAGE_NAME: python-app

# jobs:
#   build-and-push:
#     runs-on: [self-hosted, arc-org]

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v5

#       # GCP 인증
#       - name: Authenticate to Google Cloud
#         uses: google-github-actions/auth@v2
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

      # # gcloud & docker 인증 설정
      # - name: Configure Docker for GAR
      #   run: |
      #     gcloud auth configure-docker \
      #       ${{ secrets.GAR_LOCATION }}-docker.pkg.dev --quiet

      # - name: Build image
      #   run: |
      #     docker build -t \
      #       ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      # - name: Push image
      #   run: |
      #     docker push \
      #       ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # - name: Also tag & push latest
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     docker tag \
      #       ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
      #       ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

      #     docker push \
      #       ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
